blueprint:
  name: Water Leak Alert (All Moisture Sensors)
  description: >
    Sends repeating notifications for any moisture (water leak) sensor turning on.
    Notifications continue until acknowledged. Reports the exact sensor that triggered the leak.

  domain: automation

  input:
    notify_target:
      name: Notification device or group
      description: Select a single notify entity or notify group to send alerts to
      selector:
        target:
          entity:
            domain: notify

    acknowledge_helper:
      name: Acknowledge helper
      description: Select the input_boolean used to stop repeating notifications
      selector:
        entity:
          domain: input_boolean

    repeat_minutes:
      name: Notification repeat interval (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: parallel
max: 10

variables:
  notify_target: !input notify_target
  ack_helper: !input acknowledge_helper
  repeat_minutes: !input repeat_minutes

trigger:
  - platform: state
    entity_id: >
      {{
        states.binary_sensor
        | selectattr('attributes.device_class','equalto','moisture')
        | map(attribute='entity_id')
        | list
      }}
    to: "on"

action:
  # Reset acknowledgement for a new leak
  - service: input_boolean.turn_off
    target:
      entity_id: "{{ ack_helper }}"

  - repeat:
      until:
        - condition: state
          entity_id: "{{ ack_helper }}"
          state: "on"
      sequence:
        - service: notify.send_message
          target: "{{ notify_target }}"
          data:
            title: "🚨 WATER LEAK DETECTED"
            message: >
              Water leak detected at {{
                state_attr(trigger.entity_id, 'friendly_name')
              }}!
              Tap ACKNOWLEDGE once seen.
            data:
              push:
                sound:
                  name: default
                  critical: 1
                  volume: 1.0
              actions:
                - action: ACK_WATER_LEAK
                  title: "Acknowledge"
        - delay:
            minutes: "{{ repeat_minutes }}"