blueprint:
  name: Water Leak Alert – All Moisture Sensors (Manual Notify Service)
  description: >
    Sends repeating actionable notifications for any moisture (water leak) sensor.
    Notifications repeat until acknowledged.
    Users manually enter the notify service (e.g. notify.mobile_app_sams_iphone_13_pro).

  domain: automation

  input:
    notify_service:
      name: Notify service
      description: >
        Enter the full notify service name.
        Example: notify.mobile_app_sams_iphone_13_pro
      default: notify.mobile_app_your_phone_here
      selector:
        text:

    acknowledge_helper:
      name: Acknowledge helper
      description: Select the input_boolean used to stop repeated alerts
      selector:
        entity:
          domain: input_boolean

    repeat_minutes:
      name: Repeat interval (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: parallel
max: 10

variables:
  notify_service: !input notify_service
  ack_helper: !input acknowledge_helper
  repeat_minutes: !input repeat_minutes

trigger:
  - platform: state
    entity_id: >
      {{
        states.binary_sensor
        | selectattr('attributes.device_class', 'equalto', 'moisture')
        | map(attribute='entity_id')
        | list
      }}
    to: "on"

action:
  # Reset acknowledgement whenever a new leak is detected
  - service: input_boolean.turn_off
    target:
      entity_id: !input acknowledge_helper

  - repeat:
      until:
        - condition: template
          value_template: >
            {{ states(ack_helper) == 'on' }}
      sequence:
        - service: "{{ notify_service }}"
          data:
            title: "🚨 WATER LEAK DETECTED"
            message: >
              Water leak detected at
              {{ state_attr(trigger.entity_id, 'friendly_name') }}.
              Tap ACKNOWLEDGE once seen.
            data:
              push:
                sound:
                  name: default
                  critical: 1
                  volume: 1.0
              actions:
                - action: ACK_WATER_LEAK
                  title: "Acknowledge"

        - delay:
            minutes: "{{ repeat_minutes }}"