blueprint:
  name: Area-based Water Leak Alert (Acknowledgement Required, Multiple Devices)
  description: >
    Sends repeating critical notifications for any water leak sensor
    in selected areas until manually acknowledged.
    Notifications can be sent to multiple mobile devices.

  domain: automation

  input:
    leak_areas:
      name: Areas to monitor
      description: Select areas containing water leak sensors
      selector:
        area:
          multiple: true

    notify_services:
      name: Mobile notification services
      description: Select one or more mobile devices to notify
      selector:
        service:
          domain: notify
          multiple: true

    acknowledge_helper:
      name: Acknowledge helper
      description: input_boolean used to stop notifications
      selector:
        entity:
          domain: input_boolean

    repeat_minutes:
      name: Notification repeat interval (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: parallel

variables:
  areas: !input leak_areas
  notify_services: !input notify_services
  ack_helper: !input acknowledge_helper
  repeat_minutes: !input repeat_minutes

trigger:
  - platform: state
    entity_id: >
      {{
        expand(
          areas | map('area_entities') | sum(start=[])
        )
        | selectattr('domain', 'eq', 'binary_sensor')
        | selectattr('attributes.device_class', 'eq', 'moisture')
        | map(attribute='entity_id')
        | list
      }}
    to: "on"

action:
  # Reset acknowledgement for a new incident
  - service: input_boolean.turn_off
    target:
      entity_id: "{{ ack_helper }}"

  - repeat:
      until:
        - condition: state
          entity_id: "{{ ack_helper }}"
          state: "on"

      sequence:
        - repeat:
            for_each: "{{ notify_services }}"
            sequence:
              - service: "{{ repeat.item }}"
                data:
                  title: "🚨 WATER LEAK DETECTED"
                  message: >
                    Water leak detected in {{ area_name(trigger.entity_id) }}.
                    Tap ACKNOWLEDGE once you have seen this.
                  data:
                    push:
                      sound:
                        name: default
                        critical: 1
                        volume: 1.0
                    actions:
                      - action: ACK_WATER_LEAK
                        title: "Acknowledge"

        - delay:
            minutes: "{{ repeat_minutes }}"
