blueprint:
  name: Water Leak Alert (Single Notify, Area-Based)
  description: >
    Sends repeating critical notifications for any water leak sensor in selected areas until manually acknowledged.
    Supports a single mobile device or notify group as the notification target.

  domain: automation

  input:
    leak_areas:
      name: Areas to monitor
      description: Select areas containing water leak sensors
      selector:
        area:
          multiple: true

    notify_target:
      name: Notification device or group
      description: Select a single notify entity or notify group to send alerts to
      selector:
        target:
          entity:
            domain: notify

    acknowledge_helper:
      name: Acknowledge helper
      description: Input boolean used to stop repeating notifications
      selector:
        entity:
          domain: input_boolean

    repeat_minutes:
      name: Notification repeat interval (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes

mode: parallel
max: 10

variables:
  areas: !input leak_areas
  notify_target: !input notify_target
  ack_helper: !input acknowledge_helper
  repeat_minutes: !input repeat_minutes

trigger:
  - platform: state
    entity_id: >
      {{
        expand(
          areas | map('area_entities') | sum(start=[])
        )
        | selectattr('domain', 'eq', 'binary_sensor')
        | selectattr('attributes.device_class', 'eq', 'moisture')
        | map(attribute='entity_id')
        | list
      }}
    to: "on"

action:
  # Reset acknowledgement when a new leak is detected
  - service: input_boolean.turn_off
    target:
      entity_id: "{{ ack_helper }}"

  - repeat:
      until:
        - condition: state
          entity_id: "{{ ack_helper }}"
          state: "on"
      sequence:
        - service: notify.send_message
          target: "{{ notify_target }}"
          data:
            title: "🚨 WATER LEAK DETECTED"
            message: >
              Water leak detected in {{ area_name(trigger.entity_id) }}.
              Tap ACKNOWLEDGE once you have seen this.
            data:
              push:
                sound:
                  name: default
                  critical: 1
                  volume: 1.0
              actions:
                - action: ACK_WATER_LEAK
                  title: "Acknowledge"
        - delay:
            minutes: "{{ repeat_minutes }}"
